### ISSUE TITLE
missing texture information

### ISSUE THREAD

**Issue by KnudsenO** [VisMotrix/A3_MaskToSatMap_Converter#1]
Hey, your tool seems to be quite useful. Unfortunately I always get an error. "... missing texture information...", I don't really know in which direction the message should lead me. 

I also wonder if in layers.cfg the .paa should be linked. In the tutorial it is not linked. But no matter what I set in the layers.cfg. At the end I have a pink image.

maskToSatMap Log:

> INFO: Starting ...
> INFO: Reading layers.cfg
> INFO: Loading average colors from textures
> INFO: Starting sat map generation
> INFO: Building colormap from textures
> INFO: Mask loaded (20480, 20480)px
> INFO: Creating sat map
> WARNING: There is missing texture information. Areas will show as pink on sat map. Total pixel errors: 419430400
> INFO: Saving sat map
> INFO: Exporting sat map to P:/my_map/source/MaskToSat/satmap.tif
> INFO: ... Done

layers.cfg:

```

class layers
{
	class cp_concrete1
	{
		texture="DZ\surfaces\data\terrain\cp_concrete1_ca.paa";
		material="DZ\surfaces\data\terrain\cp_concrete1.rvmat";
	};	
	class cp_gravel
	{
		texture="DZ\surfaces\data\terrain\cp_gravel_ca.paa";
		material="DZ\surfaces\data\terrain\cp_gravel.rvmat";
	};	
	class sz_grass01
	{
		texture="my_map\data\surfaces\data\sz_grass02_ca.paa";
		material="my_map\data\surfaces\data\sz_grass02.rvmat";
	};	
	class sz_grass02
	{
		texture="my_map\data\surfaces\data\sz_grass01_ca.paa";
		material="my_map\data\surfaces\data\sz_grass01.rvmat";
	};
	class sz_forest01
	{
		texture="my_map\data\surfaces\data\sz_forest01_ca.paa";
		material="my_map\data\surfaces\data\sz_forest01.rvmat";
	};
	class sz_forest02
	{
		texture="my_map\data\surfaces\data\sz_forest02_ca.paa";
		material="my_map\data\surfaces\data\sz_forest02.rvmat";
	};
	class sz_forest03
	{
		texture="my_map\data\surfaces\data\sz_forest03_ca.paa";
		material="my_map\data\surfaces\data\sz_forest03.rvmat";
	};
	class sz_mud01
	{
		texture="my_map\data\surfaces\data\sz_mud01_ca.paa";
		material="my_map\data\surfaces\data\sz_mud01.rvmat";
	};
	class sz_rock01
	{
		texture="my_map\data\surfaces\data\sz_rock01_ca.paa";
		material="my_map\data\surfaces\data\sz_rock01.rvmat";
	};
	class sz_sand01
	{
		texture="my_map\data\surfaces\data\sz_sand01_ca.paa";
		material="my_map\data\surfaces\data\sz_sand01.rvmat";
	};
	class sz_soil01
	{
		texture="my_map\data\surfaces\data\sz_soil01_ca.paa";
		material="my_map\data\surfaces\data\sz_soil01.rvmat";
	};
};
class legend
{
	picture="my_map\source\maplegend.png";
	class colors
	{
		cp_concrete1[]={{203,200,199}};
		cp_gravel[]={{14,70,189}};
		sz_grass01[]={{128,197,46}};
		sz_forest01[]={{39,110,8}};
		sz_forest02[]={{232,239,33}};
		sz_forest03[]={{215,116,49}};
		sz_rock01[]={{120,115,115}};
		sz_mud01[]={{152,81,4}};
		sz_soil01[]={{255;75;10}};
	};
};
```

**Comment by KnudsenO** [comment]
Ohh, I found the solution. it was because they are textures with an alpha, so _ca.paa at the end. It seems that they have to be _co.paa textures on each.

**Comment by rk-exxec** [comment]
Hey, glad you figured it out on your own!
But its good that you mention this. We probably should support transparent textures or at least give better error messages!
